AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template to create AWS Lambda function

Globals:
  Function:
    Runtime: java11

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaDemoForYT
      Handler: org.example.LambdaYTDemo::handleRequest
      CodeUri: build/distributions/aws-lambda-sam-deploy-1.0-SNAPSHOT.zip
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
